Theta
reddign/gamers pull request #6
Opened 2024-10-08 03:01 UTC by MSmit99

Attempt 2

2024-10-22 20:48 UTC, reddign reviewed
Thanks for all your documentation notes.

Final merge approved after a rebase with main that I preformed.

2024-10-22 23:03 UTC, Owy137 requested changes

2024-10-22 23:03 UTC, Owy137 commented on web_src/general/hangmanSettings.php
Both of these should be create.php, not add.php?

2024-10-22 23:03 UTC, Owy137 commented on web_src/general/triviaSettings.php
> -            <form action="../../data_src/api/question/add.php" method="post" id="add-question" style="text-align: left">
trivia folder was renamed to question, keep what is on main branch

2024-10-22 23:03 UTC, Owy137 commented on web_src/general/register.php
> +        <form action="../../data_src/api/admin/add.php" method="post" style= "text-align: left">
These should be changed back to create.php

2024-10-22 23:03 UTC, Owy137 commented on web_src/trivia/trivia.js
> +    fetch('../../data_src/api/trivia/questions.php', {method: 'get'}) // TODO: Change file path for FTP
trivia was renamed to question, keep main branch

2024-10-23 00:37 UTC, Owy137 requested changes
Made updates to Theta branch side of merge

2024-10-23 00:42 UTC, Owy137 requested changes
Fixed reference to add.php

2024-10-26 12:22 UTC, merged